[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  targetPort = 3000
  port = 8888
  publish = "build"
  functionsPort = 9000

[context.production.environment]
  REACT_APP_ENV = "production"

[context.development.environment]
  REACT_APP_ENV = "development"

[[redirects]]
  from = "/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
